name: esqueleto-bug
version: 0.1.0.0
github: "cdparks/esqueleto-bug"
license: BSD3
author: "Christopher D. Parks"
maintainer: "christopher.daniel.parks@gmail.com"
copyright: "2021 Christopher D. Parks"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/cdparks/esqueleto-bug#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - esqueleto
  - persistent
  - persistent-template
  - text

executables:
  esqueleto-bug:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esqueleto-bug
    - monad-logger
    - persistent
    - persistent-postgresql
    - resourcet
    - text
    - unliftio-core
    - yaml
